### ISSUE TITLE
doc generated for all components creates additional '#' to appear next to names of components

### ISSUE THREAD

**Issue by n-sikka** [vuedoc/md#1]
I ran `vuedoc.md src/components/**/*.vue > docs/docs.md` to generate a common md file. 

The resulting output was somewhat like this

# Component 1
## props 
- `options` ***Array*** (*optional*) `default: [object Object]` 
Data for the Accordion 

## slots 
- `body` null 

## methods 
- `onClick()` 
Event emitted on click of the Box in the accordion. 

### props 
- `options` ***Array*** (*optional*) `default: [object Object]` 
Data for the Accordion 

### slots 
- `body` null 

### methods 
- `onClick()` 
Event emitted on click of the Box in the accordion. 

---

I see an additional '#' being appended to the next component documentation. 
Is this a bug or am i using it wrong? 

_Also would be really cool if the generator creates separate .md file for each component and picks up the name from the file._

**Comment by demsking** [comment]
hum... it's a bug... I'm going to fix it

**Comment by n-sikka** [comment]
Sweet dude! Thanks for the quick action.
Really awesome tool.

**Comment by demsking** [comment]
**This project has been moved to https://gitlab.com/vuedoc/md**
