### ISSUE TITLE
Better composition with other command line programs using stdio

### ISSUE THREAD

**Issue by mickdekkers** [vuedoc/md#3]
It would be great if we could pass file data to the CLI through `stdin` and have it output the doc results through `stdout`. This would make it easier to compose with other command line programs.

(Poor) example: we could then pass the contents of a vue file to the CLI  and get the word count of the generated documentation using this command pipeline:
```bash
$ cat some-vue-file.vue | vuedoc.md | wc -w
567
```

I suggest using something like [`get-stdin`](https://github.com/sindresorhus/get-stdin) to read stdin, and if there is some input, it can pass the generated documentation to stdout using `console.log`. If there is no input in stdin, it can fall back to the current behavior of reading the input file glob from the command line arguments.

**Comment by demsking** [comment]
Sorry, I don't understand your request. Why you could not just use:
```sh
vuedoc.md some-vue-file.vue | wc -w
567
```
?

**Comment by mickdekkers** [comment]
@demsking sorry for the confusion. The main purpose of this request is to allow the user to input the vue file contents directly, through stdin. I noticed that `@vuedoc/parser` recently got the option to pass it through `filecontent`, but if I'm not mistaken there's currently no way to do this with the `@vuedoc/md` CLI.

The `wc` command was just a simple example, but I can imagine users may want to compose this tool in more complex ways, and taking input from stdin makes that possible.

**Comment by demsking** [comment]
I just release the `v0.6.0` with the `PIPE input` support. Please read the [README](https://github.com/vuedoc/md/blob/master/README.md) file.
Thank you for your feedback

**Comment by demsking** [comment]
**This project has been moved to https://gitlab.com/vuedoc/md**
