### ISSUE TITLE
No support for computed properties

### ISSUE THREAD

**Issue by natezerk** [vuedoc/md#4]
Computed properties don't seem to get documented, could you add this please?

**Comment by demsking** [comment]
Hum... `props` and `events` are used to define the I/O Component API and sometime `methods` are also use to interact with the component. That's why there are triggered by `@vuedoc/parser`.
Could you explain your use case?

**Comment by natezerk** [comment]
Yes, so this is for use as internal documentation not just methods/events/props that are used to publically interact with the component.

**Comment by demsking** [comment]
I just release the `@vuedoc/md@0.8.0` with new

**Comment by demsking** [comment]
**This project has been moved to https://gitlab.com/vuedoc/md**
